### ISSUE TITLE
fails build with aws-sdk-cpp 1.10.30

### ISSUE THREAD

**Issue by thomas-roos** [amzn/amazon-s3-gst-plugin#29]
[error.log](https://github.com/amzn/amazon-s3-gst-plugin/files/10268030/error.log)

**Comment by quintene** [comment]
I experience the same issue.

I tried an older version of the AWS SDK C++  with the following hash which seems to be a temporary solution ; 
 git checkout 1a532d819cbeeea2f77d45085deefe3afbdb6b17

../src/gsts3multipartuploader.cpp:485:112: error: no matching function for call to 'Aws::S3::S3Client::S3Client(std::remove_reference<std::unique_ptr<Aws::Auth::AWSCredentialsProvider>&>::type, Aws::Client::Cli
entConfiguration&)'
 std::unique_ptr<Aws::S3::S3Client>(new Aws::S3::S3Client(std::move(credentials_provider), client_config)) :

**Comment by louisharris** [comment]
Commit merged to support 1.10.30: https://github.com/amzn/amazon-s3-gst-plugin/commit/b8ecca63791e6a4f9559b47d32132144d2d191ab

Let me know if this fixes your issue.

**Comment by thomas-roos** [comment]
Thank you - that fixed the issues from error.log, but then I need to patch the meson files as suggested here to fix link issues: https://github.com/amzn/amazon-s3-gst-plugin/pull/19
This is my patch which works: https://github.com/aws4embeddedlinux/meta-aws/blob/master-next/recipes-multimedia/amazon-s3-gst-plugin/files/fix-linking-of-aws-crt-cpp.patch
